# Generated by Django 5.1 on 2024-08-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_image',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='media/movie_images/'),
        ),
    ]
