# Generated by Django 5.1 on 2024-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_movie_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/movie_images/'),
        ),
    ]
