# Generated by Django 5.1 on 2024-08-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_movie_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
