# Generated by Django 5.1 on 2024-08-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_movie_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='website_url',
            new_name='website_link',
        ),
        migrations.RenameField(
            model_name='movie_link',
            old_name='url',
            new_name='link',
        ),
    ]
