# Generated by Django 5.1 on 2024-08-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_website_url_movie_website_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_link',
            old_name='website',
            new_name='origin',
        ),
    ]
