# Generated by Django 5.1 on 2024-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_website_movie_link_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='website_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
