# Generated by Django 5.1 on 2024-08-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_movie_website_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='movie_dup_title',
            options={'verbose_name': 'Доп. название', 'verbose_name_plural': 'Доп. названия'},
        ),
        migrations.AlterModelOptions(
            name='movie_image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='movie_link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='movie_tag',
            options={'verbose_name': 'Ярлык', 'verbose_name_plural': 'Ярлыки'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='website_link',
            new_name='translit_title',
        ),
    ]
